name: Auto Update Sponsor List

permissions: write-all

on:
  push:
    paths:
      - 'sponsorkit.config.js'
      - 'public/sponsors/direct-raw.json'
      - '.github/workflows/sponsor.yml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sponsor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Run Job
        run: |-
          pnpm i
          export SPONSORKIT_AFDIAN_TOKEN=${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}
          export SPONSORKIT_AFDIAN_USER_ID=${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          pnpm sponsor
          if [[ -n "$(git status -s)" ]]; then
            git add .
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git commit -m "Update Sponsor SVG"
            git push
          else
            echo "No changes detected."
          fi
