name: Auto Update Sponsor List

on:
  push:
    paths:
      - 'scripts/sponsor-*'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sponsor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: pnpm
      - run: |-
          pnpm i
          pnpm sponsor
          if [[ -n "$(git status -s)" ]]; then
            git add .
            git config user.name github-actions[bot]
            git config user.email github-actions[bot]@users.noreply.github.com
            git commit -m "Update Sponsor SVG [skip ci]"
            git push
          else
            echo "No changes detected."
          fi
